directory = "h5o2_pes"

[layer0]
name = "Gaussian"
method_basis = "B3LYP/6-31++G(d,p)"

[[tier]]

    [tier.layer_high]
    name = "NN_nop"
    method_basis = "CCSD/6-31+G(d,p)"

    [tier.layer_low]
    name = "NN_nop"
    method_basis = "B3LYP/6-31+G(d,p)"

    [tier.graph]
    cutoff = 9
    rank = 0

[molecule]
custom_node = [[0,1,2,3,4,5,6]]
charge = "water"
mesh = "NN_test_files/h5o2_coord.xyz.npz"